project_id = "uhlmwmagflzowlqxxqrp"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.sync-fio-payments]
    verify_jwt = false
